version: '3'
services:
  websocket_handler:
    build:
      context: .
      dockerfile: Dockerfile.websocket_handler
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - EVENT_HANDLER_SVC=${EVENT_HANDLER_SVC}
      - EVENT_HANDLER_PORT=${EVENT_HANDLER_PORT}
      - WS_PORT=${WS_PORT}
    ports:
      - 8008:8008
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  event_handler:
    build:
      context: .
      dockerfile: Dockerfile.event_handler
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - EVENT_HANDLER_PORT=${EVENT_HANDLER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGDATABASE_WRITE=${PGDATABASE_WRITE}
      - PGUSER_WRITE=${PGUSER_WRITE}
      - PGPASSWORD_WRITE=${PGPASSWORD_WRITE}
      - PGPORT_WRITE=${PGPORT_WRITE}
      - PGHOST_WRITE=${PGHOST_WRITE}
      - PGDATABASE_READ=${PGDATABASE_READ}
      - PGUSER_READ=${PGUSER_READ}
      - PGPASSWORD_READ=${PGPASSWORD_READ}
      - PGPORT_READ=${PGPORT_READ}
      - PGHOST_READ=${PGHOST_READ}
      - WOT_ENABLED=${WOT_ENABLED}
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=delta
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.3
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${PGDATABASE_WRITE}
      - POSTGRES_USER=${PGUSER_WRITE}
      - POSTGRES_PASSWORD=${PGPASSWORD_WRITE}
    ports:
      - 5432:5432
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.4
    command: postgres -c 'config_file=/postgresql.conf'
    volumes:
      - ./postgresql.conf:/postgresql.conf
      - ./postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER_WRITE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx-certbot:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      - DOMAIN=${DOMAIN}
      - DOCKER_SVC=172.17.0.1
      - SVC_PORT=${WS_PORT}
      - VERSION=${VERSION}
      - CONTACT=${CONTACT}
      - ADMIN_PUBKEY=${ADMIN_PUBKEY}
      - ICON=${ICON}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - websocket_handler
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.103.1
    environment:
      - DD_API_KEY=${DD_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - ./config-opentelemetry.yaml:/etc/otel/config.yaml
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.7
    ports:
      - "55680:55680"
      - "4317:4317"
    command: ["--config=/etc/otel/config.yaml"]
    group_add:
      - "999"  # Add to docker group to access docker socket
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    volumes:
      - ./tor/torrc:/etc/tor/torrc
      - ./tor/data:/var/lib/tor 
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.8
    expose:
      - "80"
    ports:
      - "9050:9050" # Expose Tor control port if needed
    depends_on:
      - websocket_handler

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - API_PORT=${API_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGDATABASE_WRITE=${PGDATABASE_WRITE}
      - PGUSER_WRITE=${PGUSER_WRITE}
      - PGPASSWORD_WRITE=${PGPASSWORD_WRITE}
      - PGPORT_WRITE=${PGPORT_WRITE}
      - PGHOST_WRITE=${PGHOST_WRITE}
      - PGDATABASE_READ=${PGDATABASE_READ}
      - PGUSER_READ=${PGUSER_READ}
      - PGPASSWORD_READ=${PGPASSWORD_READ}
      - PGPORT_READ=${PGPORT_READ}
      - PGHOST_READ=${PGHOST_READ}
    networks:
      nostpy_network:
        ipv4_address: 172.28.0.9
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  nostpy_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
